import {
  ArrowLeftRight,
  Book,
  Building2,
  Calendar,
  CalendarClock,
  CalendarRange,
  ChartColumn,
  CheckSquare,
  Clipboard,
  CreditCard,
  ExternalLink,
  EyeOff,
  FileChartColumn,
  FileText,
  History,
  Home,
  Info,
  Landmark,
  Layers,
  LayoutGrid,
  Lock,
  LogOut,
  Megaphone,
  NotepadText,
  QrCode,
  Receipt,
  Repeat,
  Scan,
  Settings,
  SquareActivity,
  SquaresIntersect,
  Table,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  Users,
  X,
  Zap,
} from "lucide-react";

export const SectionIcons = {
  studenti:   <Users size={13} />,
  nastava:    <Book size={13} />,
  evidencija: <CheckSquare size={13} />,
  analitika:  <ChartColumn size={13} />,
  forme:      <NotepadText size={13} />,
  nastavaS:   <CalendarRange size={13} />,
  evidencijaS:<CheckSquare size={13} />,
};

export const Icons = {
  clipboard:   <Building2 size={18} />,
  postClipboard: <Clipboard size={18} />,
  university:  <Landmark size={18} />,
  users:       <Users size={18} />,
  book:        <Book size={18} />,
  layers:      <Layers size={18} />,
  officeHours: <CalendarClock size={18} />,
  calendar:    <Calendar size={18} />,
  calendarAlt: <CalendarRange size={18} />,
  checkSquare: <CheckSquare size={18} />,
  barChart:    <ChartColumn size={18} />,
  qrCode:      <QrCode size={18} />,
  home:        <Home size={18} />,
  scan:        <Scan size={18} />,
  lock:        <Lock size={16} />,
  logOut:      <LogOut size={16} />,
  logOutAlt:   <LogOut size={16} />,
  user:        <User size={16} />,
  cancel:      <X size={16} />,
  report:      <FileChartColumn size={18} />,
  table:       <Table size={18} />,
  gear:        <Settings size={16} />,
  formIcon:    <NotepadText size={18} />,
  grades:      <ChartColumn size={18} />,
  activity:    <SquareActivity size={18} />,
  zap:         <Zap size={18} />,
  compare:     <ArrowLeftRight size={18} />,
  intersect:   <SquaresIntersect size={18} />,
  repeat:      <Repeat size={18} />,
  info:        <Info size={16} />,
  todos:       <CheckSquare size={18} />,
  eyeOff:      <EyeOff size={18} />,
  userMinus:   <UserMinus size={18} />,
  fileText:    <FileText size={18} />,
  megaphone:   <Megaphone size={18} />,
  grid:        <LayoutGrid size={18} />,
  userCheck:   <UserCheck size={18} />,
  fm:          <UserCog size={18} />,
  history:     <History size={18} />,
  receipt:     <Receipt size={18} />,
  externalLink: <ExternalLink size={18} />
};
