// Tapiz icon set — generic glyphs come from lucide-react, re-exported here so
// consumers keep a single import surface (`@tapizlabs/ui`). Domain-semantic
// names (University, OfficeHours, Report, ...) are curated aliases of lucide
// glyphs. Brand/domain composites that lucide cannot cover live in
// BrandIcons.tsx / LogoIcons.tsx.
export {
  Accessibility,
  Activity,
  ArrowLeft,
  ArrowRight,
  Ban,
  Bell,
  Book,
  Calendar,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clipboard,
  ClipboardCheck,
  Clock,
  Copy,
  Cpu,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Fingerprint,
  Folder,
  FolderPlus,
  GitCompare,
  Globe,
  GraduationCap,
  HardDrive,
  Hash,
  HelpCircle,
  History,
  Home,
  Image,
  Info,
  Key,
  Layers,
  Link2,
  Lock,
  LogOut,
  Mail,
  Megaphone,
  Menu,
  Monitor,
  Moon,
  Palette,
  Plus,
  Printer,
  QrCode,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  Scan,
  Search,
  Server,
  Shield,
  Smartphone,
  Star,
  Sun,
  Table,
  Tablet,
  Trophy,
  UploadCloud,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  Users,
  WifiOff,
  X,
  Zap,
  // Curated aliases — Tapiz-facing names for lucide glyphs.
  SquarePen as Edit,
  Trash2 as Trash,
  LayoutGrid as Grid,
  TriangleAlert as Alert,
  Settings as Gear,
  ChartColumn as BarChart,
  FileChartColumn as Report,
  CalendarClock as OfficeHours,
  FileUp as FileUpload,
  Landmark as University,
  Building2 as Faculty,
  SquareActivity as ActivityMenu,
  ArrowLeftRight as Compare,
  SquaresIntersect as Intersect,
  CalendarRange as CalendarWeek,
  CalendarDays as CalendarMonth,
  Hash as NumberIcon,
  Type as TextIcon,
  NotepadText as FormIcon,
  Sigma as FormulaIcon,
  ChartLine as NavAnalytics,
  ShieldCheck as NavSecurity,
} from "lucide-react";

export {
  TwoFAIcon,
  NavQrAttendance,
  NavScoresheet,
  Pdf,
  GitHubIcon,
  AppleIcon,
  GooglePlayIcon,
} from "./BrandIcons";
export type { IconProps } from "./BrandIcons";

export { Icons, SectionIcons } from "./IconMaps";
